version: '3.0'

services:
  app:
    container_name: web-enterprise-backend
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: "always"
    